import { jsPDF } from 'jspdf';
import { applyPlugin } from 'jspdf-autotable';
import { saveOrSharePdf } from './exportPdf';
applyPlugin(jsPDF);

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 15;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

const GREEN = [34, 197, 94];
const RED = [248, 113, 113];
const DARK = [51, 65, 85];
const MUTED = [148, 163, 184];
const BG_LIGHT = [248, 250, 252];
const BG_RED = [255, 245, 245];

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(MUTED[0], MUTED[1], MUTED[2]);
    doc.text(
      `Generated by NutriTrack on ${new Date().toLocaleDateString()}`,
      PAGE_WIDTH / 2,
      PAGE_HEIGHT - 10,
      { align: 'center' }
    );
  }
}

function valueOrDash(val) {
  return val && val !== 'N/A' && val !== '0' ? val : '-';
}

export async function generateNutritionPDF({ recommendedFoods, avoidFoods, categories, title = 'Nutrition Guide' }) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageW = PAGE_WIDTH;

  doc.setFontSize(22);
  doc.setTextColor(GREEN[0], GREEN[1], GREEN[2]);
  doc.text('NutriTrack', pageW / 2, 25, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(title, pageW / 2, 34, { align: 'center' });

  doc.setDrawColor(226, 232, 240);
  doc.line(MARGIN, 39, pageW - MARGIN, 39);

  doc.setFontSize(9);
  doc.setTextColor(MUTED[0], MUTED[1], MUTED[2]);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageW / 2, 47, { align: 'center' });

  let y = 55;

  for (const cat of categories) {
    const catFoods = recommendedFoods.filter(f => f.nutrient_group === cat.key);
    if (catFoods.length === 0) continue;

    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(13);
    doc.setTextColor(GREEN[0], GREEN[1], GREEN[2]);
    doc.setFont(undefined, 'bold');
    doc.text(cat.label, MARGIN, y);
    y += 7;

    const tableData = catFoods.map(food => [
      food.name,
      food.diet_type === 'Vegetarian' ? 'Veg' : food.diet_type === 'Non-Vegetarian' ? 'Non-Veg' : '-',
      food.serving_size ? food.serving_size : '-',
      valueOrDash(food.calories),
      food.benefits ? (food.benefits.length > 55 ? food.benefits.substring(0, 55) + '…' : food.benefits) : '-',
    ]);

    doc.autoTable({
      startY: y,
      head: [['Food', 'Type', 'Serving', 'Cal', 'Benefits']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: GREEN, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 7, textColor: DARK },
      alternateRowStyles: { fillColor: BG_LIGHT },
      margin: { left: MARGIN, right: MARGIN },
      styles: { cellPadding: 2 },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 16 },
        2: { cellWidth: 28 },
        3: { cellWidth: 12 },
        4: { cellWidth: 'auto' },
      },
    });

    y = doc.lastAutoTable.finalY + 8;
  }

  if (avoidFoods.length > 0) {
    if (y > 230) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(13);
    doc.setTextColor(RED[0], RED[1], RED[2]);
    doc.setFont(undefined, 'bold');
    doc.text('Foods to Avoid', MARGIN, y);
    y += 7;

    const avoidData = avoidFoods.map(food => [
      food.name,
      food.reason_to_avoid ? (food.reason_to_avoid.length > 55 ? food.reason_to_avoid.substring(0, 55) + '…' : food.reason_to_avoid) : '-',
      food.safer_alternative ? (food.safer_alternative.length > 50 ? food.safer_alternative.substring(0, 50) + '…' : food.safer_alternative) : '-',
    ]);

    doc.autoTable({
      startY: y,
      head: [['Food', 'Reason to Avoid', 'Safer Alternative']],
      body: avoidData,
      theme: 'striped',
      headStyles: { fillColor: RED, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 7, textColor: DARK },
      alternateRowStyles: { fillColor: BG_RED },
      margin: { left: MARGIN, right: MARGIN },
      styles: { cellPadding: 2 },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 75 },
        2: { cellWidth: 'auto' },
      },
    });
  }

  addFooter(doc);

  const filename = `nutrition-guide-${new Date().toISOString().split('T')[0]}.pdf`;
  await saveOrSharePdf(doc, filename);
}
